name: .NET CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: [windows-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build ./Source/stokUygulama.sln
      - name: Test
        run: dotnet test ./Source/UrunRepositoryTests/UrunRepositoryTests.csproj
      - name: Publish app artifact
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: "./bin/Release/net7.0/publish/"
      - name: Publish Infra artifact
        uses: actions/upload-artifact@v3
        with:
          name: infra
          path: "./Infra/"

  deployDevInfrastructure:
    needs: build
    name: deploy dev infrastructure
    runs-on: [windows-latest]

    steps:
      - name: Download infra
        uses: actions/download-artifact@v3
        with:
          name: infra
          path: infra
      - name: Login to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy infrastructure
        id: azure-deployment
        shell: pwsh
        run: |
          $rgName = '${{ env.RG_NAME }}'

          $(az deployment create --name $rgName `
            --location ${{ env.LOCATION }} `
            --template-file main.bicep `
            --parameters location=${{ env.LOCATION }} `
            --parameters rgName=$rgName `
            --output json) | ConvertFrom-Json
        
        working-directory: ./infra/
